# Server Configuration

[member]
members = [
  ["qi", 1, 0]
  ["ju", 1, 1]
]

[event]
events = [
  ["休假",]
  ["公勤",]
  ["任管",]
  ["補休", ]
  ["餐差", 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18,]
]

[server]
ip = "127.0.0.1"
port = "4040"
debug = true