# Server Configuration

[SERVER]
IP = "127.0.0.1"
PORT = "4040"
DEBUG = true

[[MEMBERS]]
NAME = "a"
GROUP = 1
PRIVILEGE = 1
CalendarId = "aa@group.calendar.google.com"

[[MEMBERS]]
NAME = "admin"
GROUP = 1
PRIVILEGE = 0
CalendarId = "bb@group.calendar.google.com"

[[MEMBERS]]
NAME = "c"
GROUP = 1
PRIVILEGE = 1
CalendarId = "cc@group.calendar.google.com"

[[EVENTS]]
NAME = "休假"
TIME = []

[[EVENTS]]
NAME = "公勤"
TIME = []

[[EVENTS]]
NAME = "任管"
TIME = []

[[EVENTS]]
NAME = "補休"
TIME = []

[[EVENTS]]
NAME = "餐差"
TIME = [6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18]
